### ISSUE TITLE
Upgrade vulnerable dependencies

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/upcoming-long-weekend-alexa-skill#3]
Upgrade the following dependencies in [requirements.txt](https://github.com/prabhakar267/upcoming-long-weekend-alexa-skill/blob/master/requirements.txt):
+ `cryptography` to `2.3` 
+ `flask` to `0.12.3`

**Comment by Ilyeo** [comment]
@prabhakar267 could I take this one?

**Comment by prabhakar267** [comment]
@Ilyeo Yes, go ahead!

**Comment by Ilyeo** [comment]
Hey @prabhakar267 I just opened #6 for this issue, let me know what do you think
